### PR TITLE
Set up ViewModeContext

### PR DESCRIPTION
**Pull request by zhekaiii**
@SethCKL Is this what you are talking about? A toggle on the header bar to toggle between consumer and business view, which can then propagate down to the individual components.

I'm using React's Context to do this. Using React's Context is a way of receiving data from distant parent components to avoid prop drilling (which is where parent pass down props through multiple layers of child components even though the intermediate child components do not need these data). To check for the "view mode" is now very simple:

```ts
import { useViewMode } from "@/hooks/useViewMode";

// Inside your component... 
const { viewMode } = useViewMode();
```

### CODE REVIEW

**Comment by SethCKL** [comment]
Oh yes! something like that, im wondering if we can somehow adapt the [switch](https://mantine.dev/core/switch/) component of mantine instead for something that looks like this

1_2e-PXsiDbkiZjiJQlEQCMw

**Comment by zhekaiii** [comment]
So something like what we already have ah
image

**Comment by zhekaiii** [comment]
@SethCKL like this?
https://github.com/user-attachments/assets/78a7aa7e-bf6b-4d45-b5a8-b98fbb7fb855

**Comment by SethCKL** [comment]
Looks amazing!!! and exactly what I had in mind. can remove the home page one yes!! its now redundant

**Pull request merged**
